# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates
version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
      semver-major-days: 30
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
    open-pull-requests-limit: 10
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: npm
    directory: /demo
    schedule:
      interval: monthly
    cooldown:
      default-days: 7
      semver-major-days: 30
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-major'
    open-pull-requests-limit: 5
    commit-message:
      prefix: fix(deps)

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    commit-message:
      prefix: chore(ci)
